version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alexis
      POSTGRES_PASSWORD: alexishz123
      POSTGRES_DB: nestdb
    ports:
      - "5499:5432"